apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k6-loadtester.fullname" . }}
  labels:
    {{- include "k6-loadtester.labels" . | nindent 4 }}
type: "bootstrap.kubernetes.io/token"
stringData:
{{ range $k, $v := .Values.webhook.vars }}
 {{ $k }}: {{ $v }}
{{- end }}   